apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflix-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/doyindevops/-MiniFlix-GitOps-Kind-.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
