resources:
  - namespace.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - catalog-configmap.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - miniflix-ingress.yaml
