apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflix

resources:
  - ../../base

images:
  - name: miniflix-frontend
    newName: docker.io/adedoyine/miniflix-frontend
    newTag: frontend-f93cca0
  - name: miniflix-catalog
    newName: docker.io/adedoyine/miniflix-catalog
    newTag: catalog-f93cca0
